# Generated by Django 5.0.2 on 2024-02-24 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0002_alter_subscription_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=20, verbose_name="Plan Name"),
                ),
                ("cost", models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="cost",
        ),
        migrations.AlterField(
            model_name="subscription",
            name="plan",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subscriptions",
                to="client.planmodel",
            ),
        ),
    ]
