# Generated by Django 5.0.2 on 2024-02-26 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0003_planmodel_remove_subscription_cost_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="paypal_subscription_id",
        ),
        migrations.AddField(
            model_name="planmodel",
            name="paypal_subscription_id",
            field=models.CharField(default='null', max_length=300, verbose_name="SubID"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="planmodel",
            name="cost",
            field=models.PositiveIntegerField(verbose_name="Cost"),
        ),
    ]
