# Generated by Django 5.0.2 on 2024-02-27 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0004_remove_subscription_paypal_subscription_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="planmodel",
            name="paypal_subscription_id",
        ),
        migrations.AddField(
            model_name="subscription",
            name="paypal_subscription_id",
            field=models.CharField(
                default="XXX-XXX-XXX", max_length=300, verbose_name="SubID"
            ),
        ),
    ]
