# Generated by Django 5.0.2 on 2024-03-13 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="Title")),
                ("content", models.TextField(max_length=10000, verbose_name="Content")),
                (
                    "date_posted",
                    models.DateTimeField(auto_now_add=True, verbose_name="Date posted"),
                ),
                (
                    "access_level",
                    models.CharField(
                        choices=[
                            ("Free", "free"),
                            ("Standard", "standard"),
                            ("Premium", "premium"),
                            ("Private", "private"),
                        ],
                        max_length=8,
                        verbose_name="Access Level",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        max_length=10,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Article",
                "verbose_name_plural": "Articles",
            },
        ),
    ]
