# Generated by Django 5.0.2 on 2024-02-24 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="is_premium",
        ),
        migrations.AddField(
            model_name="article",
            name="access_level",
            field=models.CharField(
                choices=[
                    ("Free", "free"),
                    ("Standard", "standard"),
                    ("Premium", "premium"),
                ],
                default=None,
                max_length=8,
                verbose_name="Access Level",
            ),
            preserve_default=False,
        ),
    ]
