# Generated by Django 5.0.2 on 2024-02-26 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0002_remove_article_is_premium_article_access_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="access_level",
            field=models.CharField(
                choices=[
                    ("Free", "free"),
                    ("Standard", "standard"),
                    ("Premium", "premium"),
                    ("Private", "private"),
                ],
                max_length=8,
                verbose_name="Access Level",
            ),
        ),
    ]
