# Generated by Django 5.0.2 on 2024-02-21 22:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="Title")),
                ("content", models.TextField(max_length=10000, verbose_name="Content")),
                (
                    "date_posted",
                    models.DateTimeField(auto_now_add=True, verbose_name="Date posted"),
                ),
                (
                    "is_premium",
                    models.BooleanField(
                        default=False, verbose_name="Is this a premium article?"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        max_length=10,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Article",
                "verbose_name_plural": "Articles",
            },
        ),
    ]
